services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST= 192.168.56.1
      - DB_USER=sa
      - DB_PASSWORD=Aryaman@1234
      - DB_NAME=MyDatabase
    depends_on: [] 